# Generated by Django 2.0.5 on 2018-11-06 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(null=True)),
                ('token_expiry', models.TextField(null=True)),
                ('token_type', models.TextField(null=True)),
                ('refresh_token', models.TextField(null=True)),
                ('api_id', models.TextField(null=True)),
                ('start_date', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='user1',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='main.Member'),
        ),
        migrations.AddField(
            model_name='group',
            name='user2',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='main.Member'),
        ),
        migrations.AddField(
            model_name='group',
            name='user3',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user3', to='main.Member'),
        ),
        migrations.AddField(
            model_name='group',
            name='user4',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user4', to='main.Member'),
        ),
        migrations.AddField(
            model_name='group',
            name='user5',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user5', to='main.Member'),
        ),
    ]
