# Generated by Django 2.0.5 on 2018-11-12 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='user1',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='main.Member'),
        ),
        migrations.AlterField(
            model_name='group',
            name='user2',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='main.Member'),
        ),
        migrations.AlterField(
            model_name='group',
            name='user3',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user3', to='main.Member'),
        ),
        migrations.AlterField(
            model_name='group',
            name='user4',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user4', to='main.Member'),
        ),
        migrations.AlterField(
            model_name='group',
            name='user5',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user5', to='main.Member'),
        ),
    ]
