# Generated by Django 2.0.5 on 2018-11-12 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181112_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='group',
            name='user2',
        ),
        migrations.RemoveField(
            model_name='group',
            name='user3',
        ),
        migrations.RemoveField(
            model_name='group',
            name='user4',
        ),
        migrations.RemoveField(
            model_name='group',
            name='user5',
        ),
        migrations.AddField(
            model_name='member',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member', to='main.Group'),
        ),
    ]
